/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kvartplata;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Саша
 */
public class Counter extends javax.swing.JFrame {

   

    public void dataBase(String query) throws ClassNotFoundException, SQLException {
        
        String driver = "org.apache.derby.jdbc.ClientDriver";//Имя драйвера
        String user = "sasha";//Логин пользователя
        String password = "sasha";//Пароль пользователя
        String url = "jdbc:derby://localhost:1527/komynPoslygu";//URL адрес
        Class.forName(driver);//Регистрируем драйвер
        Connection c = null;//Соединение с БД
        c = DriverManager.getConnection(url, user, password);//Установка соединения с БД
        Statement st = c.createStatement();//Готовим запрос
        st.executeUpdate(query);
        //st.execute(query);
       
    }
    private DefaultListModel<KomynPoslygu> model;

    /**
     * Creates new form Counter
     */
    public Counter(DefaultListModel<KomynPoslygu> model) {
        initComponents();
        this.model = model;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lichKinc = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        lichPoch = new javax.swing.JTextField();
        taruf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lichKinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lichKincActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        taruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarufActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lichKinc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lichPoch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taruf, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lichKinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lichPoch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(okButton)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
     
        KomynPoslygu a = new KomynPoslygu();
     //int id = Integer.parseInt(Id.getText());
        String nazva = a.Name;
        double lichulnukKincevuj = Double.parseDouble( lichKinc.getText()) ,
                lichulnukPochatkovuj = Double.parseDouble( lichPoch.getText()),
                taruf1 = Double.parseDouble( taruf.getText());
        
       String queryTemplate= "INSERT INTO SASHA.KOMYNPOSLYGU " +
                   "VALUES ( %d, %s, %.2f, %.2f, %.2f)";
     
   
        String query = String.format(Locale.US, queryTemplate, nazva,  lichulnukKincevuj, lichulnukPochatkovuj, taruf1);
        try {
            dataBase(query);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Counter.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Counter.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void lichKincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lichKincActionPerformed
       

    }//GEN-LAST:event_lichKincActionPerformed

    private void tarufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarufActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField lichKinc;
    public javax.swing.JTextField lichPoch;
    private javax.swing.JButton okButton;
    public javax.swing.JTextField taruf;
    // End of variables declaration//GEN-END:variables
}
