/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kvartplata;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.Locale;

/**
 *
 * @author Саша
 */
public class PaymentCounter extends javax.swing.JFrame {

    
    public DefaultListModel model;
    int payment_id;
    String sel;
    int number;
    
    ArrayList al = new ArrayList();
    ArrayList al2 = new ArrayList();
    Datas data = new Datas();
Object Array;
Object Name;
String NCL;
double NCL2;
String PCL;
double  PCL2;
String RL;
double RL2;
String CurrentName;
    
PaymentCounter(int payment_id, Object ArrayList) {
      model = new DefaultListModel();
      this.Array = ArrayList;
      sel = (String) Array;
    
        this.payment_id = payment_id;
        initComponents();
        select_counters(payment_id);
 jLabel1.setText(sel);
    }

    public void select_counters(int Flatid) {

        String driver = "org.apache.derby.jdbc.ClientDriver";//Имя драйвера
        String user = "sasha";//Логин пользователя
        String password = "sasha";//Пароль пользователя
        String url = "jdbc:derby://localhost:1527/komynPoslygu";//URL адрес

        try {
            Class.forName(driver);
            //Регистрируем драйвер
            Connection c = null;//Соединение с БД
            c = DriverManager.getConnection(url, user, password);//Установка соединения с БД
            Statement st = c.createStatement();//Готовим запрос
            String selection = "SELECT * FROM SASHA.PAYMENT_DETAILS WHERE PAYMENT_ID = %d";
            String select = String.format(selection, Flatid);
            ResultSet rs = st.executeQuery(select);

            while (rs.next()) {

                data.text = rs.getString("COUNTER_NAME");
                data.new_counter = rs.getDouble("NEW_COUNTER");
                data.previous_counter = rs.getDouble("PREVIOUS_COUNTER");
               data.rate = rs.getDouble("RATE");
                data.counter_difference = data.new_counter - data.previous_counter;
                data.total = data.counter_difference * data.rate;
                //al.add(data);
                al.add(data.new_counter);  al.add(data.previous_counter);  al.add(data.rate); al.add(data.counter_difference); al.add(data.total);
                 al2.add(data.counter_difference); al2.add(data.total);
                model.addElement(data.text);

                CounterList.setModel(model);
            }
String updation1 = "UPDATE SASHA.PAYMENT_DETAILS SET COUNTER_DIFFERENCE = %f, TOTAL = %f";
            for (int i = 0;i < al2.size(); i=i+2) {
                 
                String update1 = String.format(Locale.ENGLISH,updation1, al2.get(i), al2.get(i+1));
               st.execute(update1);
            }
        } catch (ClassNotFoundException | SQLException e) {
            String a = e.getMessage();
        }

    }
    
      public void update_counters() {

        String driver = "org.apache.derby.jdbc.ClientDriver";//Имя драйвера
        String user = "sasha";//Логин пользователя
        String password = "sasha";//Пароль пользователя
        String url = "jdbc:derby://localhost:1527/komynPoslygu";//URL адрес

        try {
            Class.forName(driver);
            //Регистрируем драйвер
            Connection c = null;//Соединение с БД
            c = DriverManager.getConnection(url, user, password);//Установка соединения с БД
            Statement st = c.createStatement();//Готовим запрос
            String update = "UPDATE SASHA.PAYMENT_DETAILS SET NEW_COUNTER = %f, PREVIOUS_COUNTER = %f, RATE = %f WHERE COUNTER_NAME = '%s'";
            String updation = String.format(update, NCL2, PCL2, RL2, CurrentName);
             st.execute(updation);

        } catch (ClassNotFoundException | SQLException e) {
            String a = e.getMessage();
        }

    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CounterList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PreviousCounterLabel = new javax.swing.JTextField();
        NewCounterLabel = new javax.swing.JTextField();
        RateLabel = new javax.swing.JTextField();
        CounterDifferenceLabel = new javax.swing.JTextField();
        TotalLabel = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CounterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CounterListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CounterList);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Previous Counter");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Counter");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rate");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Counter Difference");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PreviousCounterLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousCounterLabelActionPerformed(evt);
            }
        });

        NewCounterLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCounterLabelActionPerformed(evt);
            }
        });

        RateLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateLabelActionPerformed(evt);
            }
        });

        CounterDifferenceLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CounterDifferenceLabelActionPerformed(evt);
            }
        });

        TotalLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalLabelActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PreviousCounterLabel)
                            .addComponent(RateLabel)
                            .addComponent(NewCounterLabel)
                            .addComponent(CounterDifferenceLabel)
                            .addComponent(TotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PreviousCounterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewCounterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CounterDifferenceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PreviousCounterLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousCounterLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviousCounterLabelActionPerformed

    private void CounterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CounterListMouseClicked
        number = CounterList.getSelectedIndex();
        int i = (number)*5;
       
       String NC = Double.toString((double) al.get(i));
        NewCounterLabel.setText(NC);
         String PC = Double.toString((double) al.get(i+1));
        PreviousCounterLabel.setText(PC);
        String RA = Double.toString((double) al.get(i+2));
        RateLabel.setText(RA);
        String CD = Double.toString((double) al.get(i+3));
        CounterDifferenceLabel.setText(CD);
        String TO = Double.toString((double) al.get(i+4));
        TotalLabel.setText(TO);
        
    }//GEN-LAST:event_CounterListMouseClicked

    private void NewCounterLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCounterLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewCounterLabelActionPerformed

    private void RateLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RateLabelActionPerformed

    private void CounterDifferenceLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CounterDifferenceLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CounterDifferenceLabelActionPerformed

    private void TotalLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalLabelActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
       Name = CounterList.getSelectedValue();
       CurrentName = (String) Name;
        NCL = NewCounterLabel.getText();
        NCL2 = Double.parseDouble(NCL);
       PCL = PreviousCounterLabel.getText();
       PCL2 =Double.parseDouble(PCL);
       RL = RateLabel.getText();
       RL2 =Double.parseDouble(RL);
       model.removeAllElements();
       update_counters();
       select_counters(payment_id);
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CounterDifferenceLabel;
    private javax.swing.JList CounterList;
    private javax.swing.JTextField NewCounterLabel;
    private javax.swing.JTextField PreviousCounterLabel;
    private javax.swing.JTextField RateLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField TotalLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
