/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kvartplata;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
/**
 *
 * @author Саша
 */
public class TestJTable extends javax.swing.JFrame {

    /**
     * Creates new form TestJTable
     */
    public TestJTable() {
        initComponents();
    }
public static void createGUI() {
          JFrame frame = new JFrame("Test program");
          frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 
          String[] columnNames = {
                    "НОМЕР", "ВИД_ПОСЛУГИ",  
                    "ЛІЧИЛЬНИК_КІНЦЕВИЙ", "ЛІЧИЛЬНИК_ПОЧАТКОВИЙ",
                    "РІЗНИЦЯ_ЛІЧИЛЬНИКІВ",
                     "ТАРИФ", 
                     "СУМА"
          };
           double pokaznuk1 = 11;
           double pokaznuk2 = 9;
           double riznuc9 = pokaznuk1 - pokaznuk2;
           double taruf = 1.5;
           double syma = riznuc9 * taruf;
          Object[][] data = {
                    {"1", "Квартплата", "", "", "", "", "38,04"},
                    {"2", "Вода Холодна Туалет", pokaznuk1, pokaznuk2, riznuc9, 1.5, syma},
          };
           
          JTable table = new JTable(data, columnNames);
           
          JScrollPane scrollPane = new JScrollPane(table);
           
          frame.getContentPane().add(scrollPane);
          frame.setPreferredSize(new Dimension(1200, 400));
          frame.pack();
          frame.setLocationRelativeTo(null);
          frame.setVisible(true);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     public static void main(String[] args) {
          javax.swing.SwingUtilities.invokeLater(new Runnable() {
               public void run() {
                    JFrame.setDefaultLookAndFeelDecorated(true);
                    createGUI();
               }
          });
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
